defmodule PhoenixSpec.TypeScriptTest do
  use ExUnit.Case, async: true

  alias PhoenixSpec.TypeScript

  setup_all do
    ts = TypeScript.generate(router: TestAppWeb.Router)
    %{ts: ts}
  end

  test "generates header comment", %{ts: ts} do
    assert ts =~ "// Generated by phoenix_spec"
  end

  test "generates Post interface with correct types", %{ts: ts} do
    assert ts =~ "export interface Post {"
    assert ts =~ "id: number;"
    assert ts =~ "title: string;"
    assert ts =~ "body: string;"
    assert ts =~ "view_count: number;"
    assert ts =~ "published: boolean;"
    assert ts =~ "published_at: string;"
    assert ts =~ "author: User;"
  end

  test "generates User interface", %{ts: ts} do
    assert ts =~ "export interface User {"
    assert ts =~ "id: number;"
    assert ts =~ "name: string;"
    assert ts =~ "email: string;"
  end

  test "generates Comment interface", %{ts: ts} do
    assert ts =~ "export interface Comment {"
    assert ts =~ "id: number;"
    assert ts =~ "body: string;"
  end

  test "enum fields become union types", %{ts: ts} do
    assert ts =~ ~r/status: \("draft" \| "published" \| "archived"\);/
  end

  test "array fields use bracket syntax", %{ts: ts} do
    assert ts =~ "tags: string[];"
  end

  test "optional fields use ? syntax", %{ts: ts} do
    assert ts =~ "age?: number;"
    assert ts =~ "avatar_url?: unknown;"
  end
end
