defmodule PhoenixSpec.TypeScript do
  @moduledoc """
  Generates TypeScript type definitions from extracted view and schema information.

  Produces `.d.ts` files with interfaces matching the OpenAPI schemas.
  """

  alias PhoenixSpec.ViewExtractor
  alias PhoenixSpec.ViewExtractor.{Field, ViewInfo}

  @doc """
  Generates TypeScript type definitions from the given options.

  Same options as `PhoenixSpec.OpenAPI.generate/1`.
  """
  @spec generate(keyword()) :: String.t()
  def generate(opts \\ []) do
    router = Keyword.fetch!(opts, :router)

    json_views = PhoenixSpec.Discovery.json_views_from_router(router)
    view_infos = Enum.map(json_views, &ViewExtractor.extract/1) |> Enum.reject(&is_nil/1)

    interfaces = Enum.map(view_infos, &view_to_interface/1)

    header = "// Generated by phoenix_spec — do not edit\n\n"

    header <> Enum.join(interfaces, "\n\n") <> "\n"
  end

  defp view_to_interface(%ViewInfo{module: module, variants: variants})
       when variants != [] do
    name = ViewExtractor.view_module_to_schema_name(module)

    variant_interfaces =
      variants
      |> Enum.with_index()
      |> Enum.map(fn {%{fields: fields}, idx} ->
        variant_name = "#{name}Variant#{idx + 1}"
        props = Enum.map_join(fields, "\n", &field_to_property/1)
        {"export interface #{variant_name} {\n#{props}\n}", variant_name}
      end)

    interfaces = Enum.map_join(variant_interfaces, "\n\n", &elem(&1, 0))
    variant_names = Enum.map_join(variant_interfaces, " | ", &elem(&1, 1))
    type_alias = "export type #{name} = #{variant_names};"

    "#{interfaces}\n\n#{type_alias}"
  end

  defp view_to_interface(%ViewInfo{module: module, fields: fields}) do
    name = ViewExtractor.view_module_to_schema_name(module)
    props = Enum.map_join(fields, "\n", &field_to_property/1)

    "export interface #{name} {\n#{props}\n}"
  end

  defp field_to_property(%Field{} = field) do
    ts_type = field_to_ts_type(field)
    optional = if field.required, do: "", else: "?"

    "  #{field.name}#{optional}: #{ts_type};"
  end

  defp field_to_ts_type(%Field{ref: ref}) when is_binary(ref), do: ref

  defp field_to_ts_type(%Field{items_ref: ref}) when is_binary(ref), do: "#{ref}[]"

  defp field_to_ts_type(%Field{type: %{type: "embedded", cardinality: :one, schema: schema}}) do
    embedded_to_ts(schema)
  end

  defp field_to_ts_type(%Field{type: %{type: "embedded", cardinality: :many, schema: schema}}) do
    "#{embedded_to_ts(schema)}[]"
  end

  defp field_to_ts_type(%Field{type: %{type: "array", items: %{type: inner_type}}}) do
    "#{openapi_to_ts(inner_type)}[]"
  end

  defp field_to_ts_type(%Field{type: %{type: "string", enum: values}}) do
    values |> Enum.map_join(" | ", &inspect/1) |> then(&"(#{&1})")
  end

  defp field_to_ts_type(%Field{type: %{type: type}}) do
    openapi_to_ts(type)
  end

  defp field_to_ts_type(%Field{}), do: "unknown"

  defp embedded_to_ts(schema) do
    fields = schema.__schema__(:fields) -- [:id]

    props =
      Enum.map_join(fields, " ", fn field ->
        type = schema.__schema__(:type, field)
        ts = openapi_to_ts(PhoenixSpec.TypeMapping.to_openapi(type))
        "#{field}: #{ts};"
      end)

    "{ #{props} }"
  end

  defp openapi_to_ts(%{type: type}), do: openapi_to_ts(type)
  defp openapi_to_ts("string"), do: "string"
  defp openapi_to_ts("integer"), do: "number"
  defp openapi_to_ts("number"), do: "number"
  defp openapi_to_ts("boolean"), do: "boolean"
  defp openapi_to_ts("object"), do: "Record<string, unknown>"
  defp openapi_to_ts("array"), do: "unknown[]"
  defp openapi_to_ts(_), do: "unknown"
end
